# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
