# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='game_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
    ]
