# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_auto_20170409_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.CharField(default='', max_length=500),
        ),
    ]
